export const theme = {
  bg: {
    shell:   "var(--bg-shell)",
    pane:    "var(--bg-pane)",
    ribbon:  "var(--bg-ribbon)",
    hover:   "var(--bg-hover)",
    active:  "var(--bg-active)",
    input:   "var(--bg-input)",
    tabBar:  "var(--bg-tab-bar)",
  },
  text: {
    primary:   "var(--text-primary)",
    secondary:  "var(--text-secondary)",
    muted:     "var(--text-muted)",
    disabled:  "var(--text-disabled)",
    accent:    "var(--text-accent)",
  },
  border: {
    subtle:  "var(--border-subtle)",
    divider: "var(--border-divider)",
  },
  accent: "var(--color-accent)",
  danger: "var(--color-danger)",
  iconAccent: "var(--icon-accent)",
  treeIndent:    16,
  rowHeight:     22,
  ribbonHeight:  76,
  tabHeight:     28,
  footerHeight:  24,
  leftPaneWidth: 380,
};
