//! Excel bridge — Rust half of the StudIQ ↔ Excel live link.
//!
//! An `axum` HTTPS server on `localhost:3998`.
//! - `/api/*` routes proxy compute requests to the running StudIQ frontend via
//!   Tauri events + the `bridge_respond` command (`src-frontend/src/lib/bridge.ts`).
//! - All other paths serve the built `excel-addin/dist/` static assets, so the
//!   add-in and the API share one HTTPS origin → no mixed-content or CORS issues.
//! - TLS uses a self-signed localhost cert generated by `rcgen`, auto-installed to
//!   the Windows user Root store on first run so Excel trusts it.
//!
//! TLS is implemented via a manual `tokio-rustls` accept loop + `hyper-util`
//! connection builder — avoids `axum-server` whose dep-tree conflicts with Tauri's
//! pinned hyper version.

use std::collections::HashMap;
use std::net::SocketAddr;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;
use std::time::Duration;

use axum::{
    body::Body,
    extract::{Query, State as AxumState},
    response::IntoResponse,
    routing::{get, post},
    Json, Router,
};
use hyper_util::rt::{TokioExecutor, TokioIo};
use hyper_util::server::conn::auto::Builder as ConnBuilder;
use parking_lot::Mutex;
use serde_json::{json, Value};
use tauri::{AppHandle, Emitter};
use tokio::sync::oneshot;
use tokio_rustls::rustls::ServerConfig;
use tokio_rustls::TlsAcceptor;
use tower::ServiceExt;
use tower_http::services::ServeDir;

/// Fixed dev port. Hard-coded so `manifest.xml` can reference `https://localhost:3998`.
pub const BRIDGE_PORT: u16 = 3998;

const PROXY_TIMEOUT: Duration = Duration::from_secs(10);

pub type SharedBridge = Arc<BridgeState>;

/// Shared between the axum server (awaiting replies) and the `bridge_respond` command
/// (delivering them).
pub struct BridgeState {
    pending: Mutex<HashMap<u64, oneshot::Sender<Value>>>,
    next_id: AtomicU64,
    app: Mutex<Option<AppHandle>>,
}

impl BridgeState {
    pub fn new() -> Self {
        Self {
            pending: Mutex::new(HashMap::new()),
            next_id: AtomicU64::new(1),
            app: Mutex::new(None),
        }
    }

    /// Wire up the AppHandle for emitting events. Called in `run()` before `spawn`.
    pub fn set_app(&self, app: AppHandle) {
        *self.app.lock() = Some(app);
    }

    /// Deliver a frontend reply to the awaiting HTTP request.
    /// Called from the `bridge_respond` Tauri command.
    pub fn resolve(&self, id: u64, result: Value) {
        if let Some(tx) = self.pending.lock().remove(&id) {
            let _ = tx.send(result);
        }
    }

    /// Forward `op`/`args` to the frontend and await its JSON reply.
    async fn proxy(&self, op: &str, args: Value) -> Value {
        let id = self.next_id.fetch_add(1, Ordering::SeqCst);
        let (tx, rx) = oneshot::channel();
        self.pending.lock().insert(id, tx);

        let app = self.app.lock().clone();
        let Some(app) = app else {
            self.pending.lock().remove(&id);
            return json!({ "error": "frontend not ready" });
        };

        if app
            .emit("bridge://request", json!({ "id": id, "op": op, "args": args }))
            .is_err()
        {
            self.pending.lock().remove(&id);
            return json!({ "error": "failed to reach frontend" });
        }

        match tokio::time::timeout(PROXY_TIMEOUT, rx).await {
            Ok(Ok(v)) => v,
            _ => {
                self.pending.lock().remove(&id);
                json!({ "error": "frontend timeout" })
            }
        }
    }
}

impl Default for BridgeState {
    fn default() -> Self {
        Self::new()
    }
}

// ─── TLS cert lifecycle ───────────────────────────────────────────────────────

/// Generate (or load cached) a self-signed localhost cert in `cert_dir`.
/// On first generation, attempt to install the cert into the Windows user Root
/// store via `certutil` so Excel trusts `https://localhost:3998`.
fn ensure_dev_cert(cert_dir: &Path) -> Result<(PathBuf, PathBuf), String> {
    let cert_path = cert_dir.join("bridge-cert.pem");
    let key_path = cert_dir.join("bridge-key.pem");

    if cert_path.exists() && key_path.exists() {
        return Ok((cert_path, key_path));
    }

    std::fs::create_dir_all(cert_dir).map_err(|e| format!("cert dir: {e}"))?;

    let cert = rcgen::generate_simple_self_signed(vec!["localhost".to_string()])
        .map_err(|e| format!("rcgen: {e}"))?;
    std::fs::write(&cert_path, cert.serialize_pem().map_err(|e| format!("cert pem: {e}"))?)
        .map_err(|e| format!("write cert: {e}"))?;
    std::fs::write(&key_path, cert.serialize_private_key_pem())
        .map_err(|e| format!("write key: {e}"))?;

    tracing::info!("Excel bridge: generated dev cert at {}", cert_path.display());

    #[cfg(target_os = "windows")]
    {
        let ok = std::process::Command::new("certutil")
            .args([
                "-user",
                "-addstore",
                "-f",
                "Root",
                &cert_path.to_string_lossy(),
            ])
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .status()
            .map(|s| s.success())
            .unwrap_or(false);
        if ok {
            tracing::info!("Excel bridge: installed cert to user Root store");
        } else {
            tracing::warn!(
                "Excel bridge: certutil failed — run manually: \
                 certutil -user -addstore Root \"{}\"",
                cert_path.display()
            );
        }
    }

    Ok((cert_path, key_path))
}

fn load_tls_config(cert_path: &Path, key_path: &Path) -> Result<ServerConfig, String> {
    use rustls_pemfile::{certs, private_key};

    let cert_pem = std::fs::read(cert_path).map_err(|e| format!("read cert: {e}"))?;
    let key_pem = std::fs::read(key_path).map_err(|e| format!("read key: {e}"))?;

    let cert_chain: Vec<_> = certs(&mut cert_pem.as_slice())
        .collect::<Result<Vec<_>, _>>()
        .map_err(|e| format!("parse certs: {e}"))?;

    let key = private_key(&mut key_pem.as_slice())
        .map_err(|e| format!("parse key: {e}"))?
        .ok_or_else(|| "no private key in PEM".to_string())?;

    ServerConfig::builder()
        .with_no_client_auth()
        .with_single_cert(cert_chain, key)
        .map_err(|e| format!("TLS config: {e}"))
}

// ─── Add-in asset discovery ──────────────────────────────────────────────────

/// Find the packed 64-bit ExcelDNA XLL.
/// Search order:
///   1. `STUDIQ_XLL_PATH` env var override
///   2. `<exe_dir>/StudIQ64-packed.xll` — installed layout
///   3. `<exe_dir>/../../../excel-com-addin/bin/Release/net48/publish/StudIQ64-packed.xll` — dev
#[cfg(target_os = "windows")]
fn find_xll_path() -> Option<PathBuf> {
    if let Ok(v) = std::env::var("STUDIQ_XLL_PATH") {
        let p = PathBuf::from(v);
        if p.is_file() {
            return Some(p);
        }
    }
    if let Ok(exe) = std::env::current_exe() {
        if let Some(dir) = exe.parent() {
            let p = dir.join("StudIQ64-packed.xll");
            if p.is_file() {
                return Some(p);
            }
            // Dev workspace: exe is at target/debug|release/desktop.exe
            if let Some(root) = dir.parent().and_then(|p| p.parent()) {
                let p = root
                    .join("excel-com-addin")
                    .join("bin")
                    .join("Release")
                    .join("net48")
                    .join("publish")
                    .join("StudIQ64-packed.xll");
                if p.is_file() {
                    return Some(p);
                }
                let p = root
                    .join("excel-com-addin")
                    .join("bin")
                    .join("Debug")
                    .join("net48")
                    .join("publish")
                    .join("StudIQ64-packed.xll");
                if p.is_file() {
                    return Some(p);
                }
            }
        }
    }
    None
}

/// Register the ExcelDNA XLL in `HKCU\Software\Microsoft\Office\16.0\Excel\Options`
/// using the first available `OPEN` / `OPEN1` … `OPEN9` slot.
/// Records which slot was used in `HKCU\Software\StudIQ\ExcelAddinOpenSlot`
/// so the uninstaller can remove the right entry.
/// Idempotent — re-checks on every app start.
#[cfg(target_os = "windows")]
fn ensure_xll_registered() {
    use winreg::enums::{HKEY_CURRENT_USER, KEY_READ, KEY_WRITE};
    use winreg::RegKey;

    let xll_path = match find_xll_path() {
        Some(p) => p,
        None => {
            tracing::warn!("Excel bridge: StudIQ64-packed.xll not found — skipping Excel registration");
            return;
        }
    };

    let xll_str = xll_path.to_string_lossy();
    let expected_val = format!("/R \"{}\"", xll_str);
    let hkcu = RegKey::predef(HKEY_CURRENT_USER);
    let opts_path = r"Software\Microsoft\Office\16.0\Excel\Options";

    let opts_key = match hkcu.create_subkey_with_flags(opts_path, KEY_READ | KEY_WRITE) {
        Ok((k, _)) => k,
        Err(e) => {
            tracing::warn!("Excel bridge: cannot open Excel\\Options registry key: {e}");
            return;
        }
    };

    // Check if already registered in any slot.
    for i in 0..=9usize {
        let name = if i == 0 { "OPEN".to_string() } else { format!("OPEN{}", i) };
        if let Ok(val) = opts_key.get_value::<String, _>(&name) {
            if val == expected_val {
                tracing::debug!("Excel bridge: XLL already registered at Excel\\Options\\{}", name);
                return;
            }
        }
    }

    // Write to the first empty slot.
    for i in 0..=9usize {
        let name = if i == 0 { "OPEN".to_string() } else { format!("OPEN{}", i) };
        if opts_key.get_value::<String, _>(&name).is_err() {
            match opts_key.set_value(&name, &expected_val.as_str()) {
                Ok(_) => {
                    tracing::info!("Excel bridge: registered XLL at Excel\\Options\\{}", name);
                    // Record the slot name so the uninstaller can clean it up.
                    if let Ok((studiq_key, _)) =
                        hkcu.create_subkey_with_flags(r"Software\StudIQ", KEY_WRITE)
                    {
                        let _ = studiq_key.set_value("ExcelAddinOpenSlot", &name.as_str());
                    }
                }
                Err(e) => tracing::warn!("Excel bridge: failed to write XLL registry entry: {e}"),
            }
            return;
        }
    }

    tracing::warn!("Excel bridge: all Excel OPEN slots occupied — XLL not registered");
}

#[cfg(not(target_os = "windows"))]
fn ensure_xll_registered() {}

/// Find the built `excel-addin/dist/` directory.
/// Search order:
///   1. `STUDIQ_ADDIN_DIST` env var override
///   2. `<exe_dir>/excel-addin/dist/`  — installed layout
///   3. `<exe_dir>/../../../excel-addin/dist/` — dev workspace layout
fn find_addin_dist() -> Option<PathBuf> {
    // Explicit override always wins.
    if let Ok(v) = std::env::var("STUDIQ_ADDIN_DIST") {
        let p = PathBuf::from(v);
        if p.is_dir() {
            return Some(p);
        }
    }

    // Debug builds: path is baked in at compile time from CARGO_MANIFEST_DIR
    // (desktop/), so we always land on the workspace excel-addin/dist/ and
    // `npm run build` is picked up immediately — no Rust rebuild needed.
    #[cfg(debug_assertions)]
    {
        let p = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .map(|root| root.join("excel-addin").join("dist"));
        if let Some(p) = p {
            if p.is_dir() {
                return Some(p);
            }
        }
    }

    // Release / installed layout: excel-addin/dist is placed next to the exe.
    if let Ok(exe) = std::env::current_exe() {
        if let Some(dir) = exe.parent() {
            let p = dir.join("excel-addin").join("dist");
            if p.is_dir() {
                return Some(p);
            }
        }
    }
    None
}


// ─── Server spawn ─────────────────────────────────────────────────────────────

/// Spawn the HTTPS bridge on the Tauri async runtime.
///
/// `cert_dir` — where to store / find the dev cert (app data dir / "bridge").
pub fn spawn(state: SharedBridge, cert_dir: PathBuf) {
    ensure_xll_registered();
    tauri::async_runtime::spawn(async move {
        let (cert_path, key_path) = match ensure_dev_cert(&cert_dir) {
            Ok(v) => v,
            Err(e) => {
                tracing::error!("Excel bridge cert: {e}");
                return;
            }
        };

        let tls_cfg = match load_tls_config(&cert_path, &key_path) {
            Ok(v) => v,
            Err(e) => {
                tracing::error!("Excel bridge TLS: {e}");
                return;
            }
        };

        let addin_dist = find_addin_dist();
        match &addin_dist {
            Some(p) => tracing::info!("Excel bridge: serving add-in from {}", p.display()),
            None => tracing::info!(
                "Excel bridge: no excel-addin/dist found — run `npm run build` in excel-addin/"
            ),
        }

        // Build router: API routes first; static assets as fallback.
        let router: Router = {
            let base = Router::new()
                .route("/api/ping", get(ping))
                .route("/api/groups", get(groups))
                .route("/api/quantity", get(quantity))
                .route("/api/measurements", get(measurements))
                .route("/api/measurement", get(measurement))
                .route("/api/framing", get(framing))
                .route("/api/framing_size", get(framing_size))
                .route("/api/lintel_size", get(lintel_size))
                .route("/api/rates", get(rates))
                .route("/api/rate", get(rate_by_id))
                .route("/api/constants", get(constants))
                .route("/api/constant", get(constant_by_name))
                .route("/api/focus", post(focus))
                .with_state(Arc::clone(&state));
            match addin_dist {
                Some(dist) => base.fallback_service(ServeDir::new(dist)),
                None => base,
            }
        };

        let addr: SocketAddr = format!("127.0.0.1:{BRIDGE_PORT}")
            .parse()
            .expect("valid addr");
        let listener = match tokio::net::TcpListener::bind(addr).await {
            Ok(l) => l,
            Err(e) => {
                tracing::error!("Excel bridge bind: {e}");
                return;
            }
        };
        let tls_acceptor = TlsAcceptor::from(Arc::new(tls_cfg));
        tracing::info!("Excel bridge listening on https://127.0.0.1:{BRIDGE_PORT}");

        loop {
            let (tcp_stream, _) = match listener.accept().await {
                Ok(v) => v,
                Err(e) => {
                    tracing::error!("Excel bridge accept: {e}");
                    continue;
                }
            };
            let tls_acceptor = tls_acceptor.clone();
            let router = router.clone();

            tokio::spawn(async move {
                let tls_stream = match tls_acceptor.accept(tcp_stream).await {
                    Ok(s) => s,
                    Err(_) => return, // TLS handshake failures are common (e.g. plain-HTTP probes)
                };
                let io = TokioIo::new(tls_stream);

                // Wrap the Tower service in a Hyper service, converting the
                // incoming body type to axum's Body via Body::new.
                let service = hyper::service::service_fn(move |req: hyper::Request<hyper::body::Incoming>| {
                    let app = router.clone();
                    async move { app.oneshot(req.map(Body::new)).await }
                });

                ConnBuilder::new(TokioExecutor::new())
                    .serve_connection(io, service)
                    .await
                    .ok();
            });
        }
    });
}

// ─── Route handlers ───────────────────────────────────────────────────────────

async fn ping(AxumState(state): AxumState<SharedBridge>) -> impl IntoResponse {
    Json(state.proxy("ping", json!({})).await)
}

async fn groups(AxumState(state): AxumState<SharedBridge>) -> impl IntoResponse {
    Json(state.proxy("groups", json!({})).await)
}

async fn quantity(
    AxumState(state): AxumState<SharedBridge>,
    Query(params): Query<HashMap<String, String>>,
) -> impl IntoResponse {
    let args = json!({
        "groupId": params.get("groupId"),
        "display": params.get("display"),
    });
    Json(state.proxy("quantity", args).await)
}

async fn measurements(
    AxumState(state): AxumState<SharedBridge>,
    Query(params): Query<HashMap<String, String>>,
) -> impl IntoResponse {
    let args = json!({
        "groupId": params.get("groupId"),
        "display": params.get("display"),
    });
    Json(state.proxy("measurements", args).await)
}

async fn measurement(
    AxumState(state): AxumState<SharedBridge>,
    Query(params): Query<HashMap<String, String>>,
) -> impl IntoResponse {
    let args = json!({
        "groupId": params.get("groupId"),
        "measurementId": params.get("measurementId"),
        "display": params.get("display"),
    });
    Json(state.proxy("measurement", args).await)
}

async fn framing(
    AxumState(state): AxumState<SharedBridge>,
    Query(params): Query<HashMap<String, String>>,
) -> impl IntoResponse {
    let args = json!({ "groupId": params.get("groupId") });
    Json(state.proxy("framing", args).await)
}

async fn framing_size(
    AxumState(state): AxumState<SharedBridge>,
    Query(params): Query<HashMap<String, String>>,
) -> impl IntoResponse {
    let args = json!({ "groupId": params.get("groupId") });
    Json(state.proxy("framing_size", args).await)
}

async fn lintel_size(
    AxumState(state): AxumState<SharedBridge>,
    Query(params): Query<HashMap<String, String>>,
) -> impl IntoResponse {
    let args = json!({
        "groupId": params.get("groupId"),
        "size": params.get("size"),
    });
    Json(state.proxy("lintel_size", args).await)
}

async fn rates(AxumState(state): AxumState<SharedBridge>) -> impl IntoResponse {
    Json(state.proxy("rates", json!({})).await)
}

async fn rate_by_id(
    AxumState(state): AxumState<SharedBridge>,
    Query(params): Query<HashMap<String, String>>,
) -> impl IntoResponse {
    let args = json!({ "id": params.get("id") });
    Json(state.proxy("rate", args).await)
}

async fn constants(AxumState(state): AxumState<SharedBridge>) -> impl IntoResponse {
    Json(state.proxy("constants", json!({})).await)
}

async fn constant_by_name(
    AxumState(state): AxumState<SharedBridge>,
    Query(params): Query<HashMap<String, String>>,
) -> impl IntoResponse {
    let args = json!({ "name": params.get("name") });
    Json(state.proxy("constant", args).await)
}

async fn focus(
    AxumState(state): AxumState<SharedBridge>,
    Json(body): Json<Value>,
) -> impl IntoResponse {
    let args = json!({ "groupId": body.get("groupId") });
    Json(state.proxy("focus", args).await)
}
